In [31]:
import itertools as it
from itertools import combinations
import numpy as np


In [32]:
iterable = [2, 10, 20, 15]
r =3
hola = list(it.combinations(iterable, r))
print(hola)

[(2, 10, 20), (2, 10, 15), (2, 20, 15), (10, 20, 15)]


In [33]:
arr = np.array(hola)
print(arr)

[[ 2 10 20]
 [ 2 10 15]
 [ 2 20 15]
 [10 20 15]]


In [80]:
lst=[]
for i in hola:
    var1=i[0]*i[1]*i[2]
    lst.append(var1)
print(lst)
    

[400, 300, 600, 3000]


In [81]:

lst=[]
for i in hola:
    var1=1
    for e in range (len(i)): 
        var1=var1*i[e]
    lst.append(var1)
print(lst)

[400, 300, 600, 3000]


In [103]:
from functools import reduce
lst2= []
for i in hola:
    lst2.append(reduce(lambda x, y: x*y,i))
lst2

[400, 300, 600, 3000]

In [132]:
lst3 = [reduce(lambda x, y: x*y,i) for i in hola]
lst3

[400, 300, 600, 3000]

In [133]:
sums = list(it.combinations(lst3, 2))
sums

[(400, 300), (400, 600), (400, 3000), (300, 600), (300, 3000), (600, 3000)]

In [149]:
addens = [reduce(lambda x, y: x+y,i) for i in sums]
addens

[700, 1000, 3400, 900, 3300, 3600]

In [151]:
addens = [sum(i) for i in sums]
addens

[700, 1000, 3400, 900, 3300, 3600]

In [135]:
count1 = 0
count2 = 0
count3 = 0
max_val = 8
for i in addens:
    if i < max_val:
        count1 += 1
    elif i == max_val:
        count2 += 1
    else:
        count3 += 1
print(count1,count2,count3)

0 0 6


In [146]:
lst7 = [2, 10, '20', 15]
for i in lst7:
    if isinstance(i, str) or isinstance(i, float):
        print("Error. Unexpected entries")


Error. Unexpected entries


In [156]:
lst = [2, 10, 20, 15]

num_fact = 3
num_add = 38
max_val = 8
v = list(it.combinations(list(len(lst)), num_fact))
v


TypeError: 'int' object is not iterable