In [31]:
import itertools as it
from itertools import combinations
import numpy as np


In [32]:
iterable = [2, 10, 20, 15]
r =3
hola = list(it.combinations(iterable, r))
print(hola)

[(2, 10, 20), (2, 10, 15), (2, 20, 15), (10, 20, 15)]


In [33]:
arr = np.array(hola)
print(arr)

[[ 2 10 20]
 [ 2 10 15]
 [ 2 20 15]
 [10 20 15]]


In [47]:
new_lst=1
lst=[]
for i in hola:
    lst_2=[]
    for e in range(len(i)):
        new_var=i*i[e]
        print(new_var)
    

(2, 10, 20, 2, 10, 20)
(2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20)
(2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20, 2, 10, 20)
(2, 10, 15, 2, 10, 15)
(2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15)
(2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15, 2, 10, 15)
(2, 20, 15, 2, 20, 15)
(2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15)
(2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2, 20, 15, 2